package io.github.gourdoni.declension.persistence;

import io.github.gourdoni.declension.domain.DataAccessException;
import io.github.gourdoni.declension.domain.ReferenceRepository;
import io.github.gourdoni.declension.domain.ReferenceEntity;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * JDBC core shared by every language-scoped entity.
 */
abstract class SQLiteReferenceRepository<T extends ReferenceEntity> implements ReferenceRepository<T> {

    private final Database database;

    protected SQLiteReferenceRepository(Database database) {
        this.database = database;
    }

    protected abstract String tableTitle();

    protected abstract List<String> editableAttributes();

    protected abstract void substituteEditableAttributes(PreparedStatement statement, T value) throws SQLException;

    protected abstract T readRecord(ResultSet queryResult) throws SQLException;

    protected abstract T usingGeneratedID(T entity, long id);

    // Default to lexicographic order of titles.
    protected String orderByAttribute() {
        return "title";
    }

    @Override
    public T save(T entity) {
        return entity.id() == 0 ? insert(entity) : update(entity);
    }

    private T insert(T entity) {
        // Prepare SQL including placeholder `?` tokens.
        String sql = "INSERT INTO " + tableTitle() + " (" + editableAttributeList() + ") VALUES (" + placeholders(editableAttributes().size()) + ")";
        try (Connection connection = database.openConnection(); PreparedStatement statement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            // Substitute actual tuple/record/entity values into placeholders; defined on a per-entity basis.
            substituteEditableAttributes(statement, entity);
            statement.executeUpdate();
            // Update entity to use real ID value generated by database (instead of the original zero for unsaved entities).
            try (ResultSet keys = statement.getGeneratedKeys()) {
                keys.next();
                return usingGeneratedID(entity, keys.getLong(1));
            }
        } catch (SQLException exception) {
            throw new DataAccessException("Failed to insert into " + tableTitle(), exception);
        }
    }

    private T update(T entity) {
        // Prepare SQL including placeholder `?` tokens.
        String sql = "UPDATE " + tableTitle() + " SET " + assignPlaceholderList() + " WHERE id = ?";
        try (Connection connection = database.openConnection(); PreparedStatement statement = connection.prepareStatement(sql)) {
            // Substitute actual tuple/record/entity values into placeholders; defined on a per-entity basis.
            substituteEditableAttributes(statement, entity);
            // Add 1 here for final `id = ?` placeholder.
            statement.setLong(editableAttributes().size() + 1, entity.id());
            statement.executeUpdate();
            return entity;
        } catch (SQLException exception) {
            throw new DataAccessException("Failed to update " + tableTitle() + " id " + entity.id(), exception);
        }
    }

    @Override
    public List<T> findByLanguage(long languageID) {
        String sql = "SELECT id, " + editableAttributeList() + " FROM " + tableTitle() + " WHERE language_id = ? ORDER BY " + orderByAttribute();
        try (Connection connection = database.openConnection(); PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setLong(1, languageID);
            try (ResultSet queryResult = statement.executeQuery()) {
                List<T> entities = new ArrayList<>();
                while (queryResult.next()) {
                    entities.add(readRecord(queryResult));
                }
                return entities;
            }
        } catch (SQLException exception) {
            throw new DataAccessException("Could not list " + tableTitle() + " for language " + languageID, exception);
        }
    }

    private String editableAttributeList() {
        return String.join(", ", editableAttributes());
    }

    private String assignPlaceholderList() {
        return String.join(", ", editableAttributes().stream().map(attribute -> attribute + " = ?").toList());
    }

    private static String placeholders(int count) {
        return String.join(", ", Collections.nCopies(count, "?"));
    }
}
